services:
  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    container_name: discovery-server
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8761/"]
      interval: 10s
      retries: 6
      start_period: 30s
      timeout: 5s

  config-server:
    build:
      context: ./config-server
    ports:
      - "8283:8283"
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8283/config/actuator/health"]
      interval: 30s
      retries: 7
      start_period: 60s
      timeout: 10s

  auth-service:
    build:
      context: ./auth
    ports:
      - "8081:8081"
    container_name: auth-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      db-auth:
        condition: service_healthy

  stock-service:
    build:
      context: ./stock
    ports:
      - "8290:8290"
    container_name: stock-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      db-stock:
        condition: service_healthy

  db-auth:
    image: postgres
    container_name: db-auth
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: users-auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234@
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d users-auth"]
      interval: 20s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db_auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db-stock:
    image: postgres
    container_name: db-stock
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: stock-database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234@
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d stock-database"]
      interval: 20s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db_stock_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "3080:8080"

volumes:
  db_auth_data:
  db_stock_data:
