services:
  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    container_name: discovery-server
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8761/"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s

  config-server:
    build:
      context: ./config-server
    ports:
      - "8283:8283"
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8283/config/actuator/health"]
      interval: 20s
      retries: 5
      start_period: 30s
      timeout: 10s

  auth-service:
    build:
      context: ./auth
    ports:
      - "8081:8081"
    container_name: auth-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      db-auth:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  stock-service:
    build:
      context: ./stock
    ports:
      - "8290:8290"
    container_name: stock-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      db-stock:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8290/actuator/health"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  menu-service:
    build:
      context: ./menu-service
    ports:
      - "8484:8484"
    container_name: menu-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      db-menu:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8484/actuator/health"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  db-auth:
    image: postgres
    container_name: db-auth
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: users-auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234@
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d users-auth"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 10s
    volumes:
      - db_auth_data:/var/lib/postgresql/data

  db-stock:
    image: postgres
    container_name: db-stock
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: stock-database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234@
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d stock-database"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 10s
    volumes:
      - db_stock_data:/var/lib/postgresql/data

  db-menu:
    image: postgres
    container_name: db-menu
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: menu-database
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: thg1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thiago -d menu-database"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 10s
    volumes:
      - db_menu_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "3080:8080"

volumes:
  db_auth_data:
  db_stock_data:
  db_menu_data: