server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://config-server:8283/config
      fail-fast: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
