server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: configserver:http://config-server:8283/config?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100
  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      ddl-auto: ${hibernate-ddl-auto}
    show-sql: ${jpa-show-sql}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops
  endpoint:
    env:
      enabled: true
      show-values: ALWAYS
      keys-to-sanitize: 
    configprops:
      show-values: ALWAYS
