spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://localhost:8283/config

  datasource:
    url: jdbc:postgresql://localhost:5432/users-auth
    username: admin
    password: admin1234@
  flyway:
    baseline-on-migrate: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
