server:
  port: 8081

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    lazy-initialization: true
  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      ddl-auto: ${hibernate-ddl-auto}
    show-sql: ${jpa-show-sql}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
