server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://localhost:8283/config

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
