spring:
  application:
    name: auth-application
  cloud:
    config:
      uri: http://localhost:8283/config

  datasource:
    url: jdbc:postgresql://localhost:5432/public
    username: admin
    password: admin1234@
  flyway:
    baseline-on-migrate: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
