version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: thg1234
      POSTGRES_DB: menu
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: menu-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/menu
      SPRING_DATASOURCE_USERNAME: thiago
      SPRING_DATASOURCE_PASSWORD: thg1234
    ports:
      - "8080:8080"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
