spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/menu
    username: thiago
    password: thg1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
