spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ThSFernandes/config-repo.git
          clone-on-start: true
        fail-fast: true

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.springframework.cloud.config.client: DEBUG
    org.springframework.boot.actuate.health: DEBUG

server:
  port: 8283
  servlet:
    context-path: /config

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
