spring:
  application:
    name: Config_Server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: https://github.com/ThSFernandes/config-repo.git
          search-paths: '{application}'
          clone-on-start: true

server:
  port: 8283
  servlet:
    context-path: /config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

